In [9]:
import numpy as np
import pandas as pd

In [10]:
times=pd.read_csv(r"C:\Users\SHILA\OneDrive\Desktop\PYTHON\ML_practiceDays\Datasets\messages.csv")
dates=pd.read_csv(r"C:\Users\SHILA\OneDrive\Desktop\PYTHON\ML_practiceDays\Datasets\orders.csv")

In [11]:
dates.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [12]:
times.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [13]:
dates.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [14]:
times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [ ]:
dates.describe() # only numeric vals, time is not numeric

        product_id      city_id       orders
count  1000.000000  1000.000000  1000.000000
mean   3826.379000    16.371000    17.497000
std    2217.585914     8.554211    57.357841
min       5.000000     0.000000     1.000000
25%    1935.000000    13.000000     1.000000
50%    3810.000000    16.000000     4.000000
75%    5778.000000    25.000000    12.000000
max    7585.000000    30.000000  1004.000000

In [ ]:
times.describe()

                       date                                          msg
count                  1000                                         1000
unique                  999                                          966
top     2013-11-01 23:36:00  ласковая кошечка ищет своего ночного котика
freq                      2                                            4

In [17]:
# convert to date_time
dates['date']=pd.to_datetime(dates['date'])

In [ ]:
dates.info() # date col data type is now datetime64

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

In [ ]:
# extract year
dates['year']=dates['date'].dt.year

In [20]:
dates.head()

        date  product_id  city_id  orders  year
0 2019-12-10        5628       25       3  2019
1 2018-08-15        3646       14     157  2018
2 2018-10-23        1859       25       1  2018
3 2019-08-17        7292       25       1  2019
4 2019-01-06        4344       25       3  2019

In [ ]:
# extract month
dates['month']=dates['date'].dt.month

In [22]:
dates.head()

        date  product_id  city_id  orders  year  month
0 2019-12-10        5628       25       3  2019     12
1 2018-08-15        3646       14     157  2018      8
2 2018-10-23        1859       25       1  2018     10
3 2019-08-17        7292       25       1  2019      8
4 2019-01-06        4344       25       3  2019      1

In [ ]:
# extract month name
dates['month_names']=dates['date'].dt.month_name()

In [24]:
dates.head()

        date  product_id  city_id  orders  year  month month_names
0 2019-12-10        5628       25       3  2019     12    December
1 2018-08-15        3646       14     157  2018      8      August
2 2018-10-23        1859       25       1  2018     10     October
3 2019-08-17        7292       25       1  2019      8      August
4 2019-01-06        4344       25       3  2019      1     January

In [ ]:
# extract day
dates['day']=dates['date'].dt.day

In [26]:
dates.head()

        date  product_id  city_id  orders  year  month month_names  day
0 2019-12-10        5628       25       3  2019     12    December   10
1 2018-08-15        3646       14     157  2018      8      August   15
2 2018-10-23        1859       25       1  2018     10     October   23
3 2019-08-17        7292       25       1  2019      8      August   17
4 2019-01-06        4344       25       3  2019      1     January    6

In [ ]:
# extract day of the week
dates["day_ofWeek"]=dates['date'].dt.day_of_week

In [28]:
dates.head()

,date,product_id,city_id,orders,year,month,month_names,day,day_ofWeek
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [ ]:
# extract day name
dates['day_name']=dates['date'].dt.day_name()

In [33]:
dates.drop(columns=['product_id','city_id','orders']).head() # monday= 0, tuesday= 1,.....sunday= 6

        date  year  month month_names  day  day_ofWeek   day_name
0 2019-12-10  2019     12    December   10           1    Tuesday
1 2018-08-15  2018      8      August   15           2  Wednesday
2 2018-10-23  2018     10     October   23           1    Tuesday
3 2019-08-17  2019      8      August   17           5   Saturday
4 2019-01-06  2019      1     January    6           6     Sunday

In [ ]:
# check if it is weekend
dates['is_weekend']=np.where(dates['day_name'].isin(['Saturday','Sunday']),1,0) # 1 if true else 0 (false)
dates.drop(columns=['product_id','city_id','orders']).head()

        date  year  month month_names  day  day_ofWeek   day_name  is_weekend
0 2019-12-10  2019     12    December   10           1    Tuesday           0
1 2018-08-15  2018      8      August   15           2  Wednesday           0
2 2018-10-23  2018     10     October   23           1    Tuesday           0
3 2019-08-17  2019      8      August   17           5   Saturday           1
4 2019-01-06  2019      1     January    6           6     Sunday           1

In [36]:
# extract week
dates['weeks_no']=dates['date'].dt.isocalendar().week
dates.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_names,day,day_ofWeek,day_name,is_weekend,weeks_no
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [ ]:
# quarter of the year
dates['quarter']=dates['date'].dt.quarter
dates.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_names,day,day_ofWeek,day_name,is_weekend,weeks_no,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [38]:
# semester of the year
dates['semester']=np.where(dates['quarter'].isin([1,2]), 1, 2)
dates.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_names,day,day_ofWeek,day_name,is_weekend,weeks_no,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [40]:
# check current date time
import datetime
today=datetime.datetime.today()
today # (year, month, day, hour, minutes, seconds, miliseconds)

datetime.datetime(2026, 9, 27, 18, 23, 52, 417401)

In [ ]:
today - dates['date'] # gap between today and every day of the dataset in days, with current time

0     2483 days 18:23:52.417401
1     2965 days 18:23:52.417401
2     2896 days 18:23:52.417401
3     2598 days 18:23:52.417401
4     2821 days 18:23:52.417401
                 ...
995   2911 days 18:23:52.417401
996   2852 days 18:23:52.417401
997   2700 days 18:23:52.417401
998   2765 days 18:23:52.417401
999   2539 days 18:23:52.417401
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
(today - dates['date']).dt.days # gap between today and every day of the dataset in days

0      2483
1      2965
2      2896
3      2598
4      2821
       ...
995    2911
996    2852
997    2700
998    2765
999    2539
Name: date, Length: 1000, dtype: int64

In [49]:
# months passed between current day and dataset dates
np.round((today - dates['date']) / np.timedelta64(30, 'D'),0)

0      83.0
1      99.0
2      97.0
3      87.0
4      94.0
       ...
995    97.0
996    95.0
997    90.0
998    92.0
999    85.0
Name: date, Length: 1000, dtype: float64

In [50]:
# wor on time data
times.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [ ]:
times['date']=pd.to_datetime(times['date']) # datatype is now dattime64
times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [ ]:
# extract hour, min, sec
times['hour']=times['date'].dt.hour
times['min']=times['date'].dt.minute
times['sec']=times['date'].dt.second

times.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [54]:
# extract only time
times['time']=times['date'].dt.time
times.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [ ]:
# time differece between today and dataset times
today - times['date'] # days and time

0     4669 days 17:33:52.417401
1     4533 days 18:43:52.417401
2     5019 days 18:02:52.417401
3     4321 days 17:52:52.417401
4     4718 days 19:12:52.417401
                 ...
995   5308 days 17:33:52.417401
996   4629 days 19:09:52.417401
997   5094 days 18:46:52.417401
998   5210 days 18:49:52.417401
999   4482 days 18:58:52.417401
Name: date, Length: 1000, dtype: timedelta64[ns]

In [ ]:
# time differece between today and dataset given times in seconds
(today - times['date'])/np.timedelta64(1, 's') # +08 means to the power 10

0      4.034648e+08
1      3.917186e+08
2      4.337066e+08
3      3.733988e+08
4      4.077044e+08
           ...
995    4.586744e+08
996    4.000146e+08
997    4.401892e+08
998    4.502118e+08
999    3.873131e+08
Name: date, Length: 1000, dtype: float64

In [57]:
# time differece between today and dataset given times in minutes
(today - times['date'])/np.timedelta64(1, 'm') # +06 means to the power 10

0      6.724414e+06
1      6.528644e+06
2      7.228443e+06
3      6.223313e+06
4      6.795073e+06
           ...
995    7.644574e+06
996    6.666910e+06
997    7.336487e+06
998    7.503530e+06
999    6.455219e+06
Name: date, Length: 1000, dtype: float64

In [ ]:
# time differece between today and dataset given times in hours
(today - times['date'])/np.timedelta64(1, 'h')

0      112073.564560
1      108810.731227
2      120474.047894
3      103721.881227
4      113251.214560
           ...
995    127409.564560
996    111115.164560
997    122274.781227
998    125058.831227
999    107586.981227
Name: date, Length: 1000, dtype: float64